
training_pipeline_config:
 pipeline_name: src
 artifact_dir: artifact



data_ingestion_config:
 data_download_url: https://raw.githubusercontent.com/sunil-dhakad/data-folder/main/marketing_campaign.csv
 raw_data_dir: raw_data
 ingested_train_dir: ingested_train_data

