name: marketing_campaign.csv
columns:
  AcceptedCmp1: int
  AcceptedCmp2: int
  AcceptedCmp3: int
  AcceptedCmp4: int
  AcceptedCmp5: int
  Complain: int
  Dt_Customer: category
  Education: category
  ID: int
  Income: float
  Kidhome: int
  Marital_Status: category
  MntFishProducts: int
  MntFruits: int
  MntGoldProds: int
  MntMeatProducts: int
  MntSweetProducts: int
  MntWines: int
  NumCatalogPurchases: int
  NumDealsPurchases: int
  NumStorePurchases: int
  NumWebPurchases: int
  NumWebVisitsMonth: int
  Recency: int
  Response: int
  Teenhome: int
  Year_Birth: int
  Z_CostContact: int
  Z_Revenue: int
numerical_columns:
  AcceptedCmp1: int
  AcceptedCmp2: int
  AcceptedCmp3: int
  AcceptedCmp4: int
  AcceptedCmp5: int
  Complain: int
  ID: int
  Income: float
  Kidhome: int
  MntFishProducts: int
  MntFruits: int
  MntGoldProds: int
  MntMeatProducts: int
  MntSweetProducts: int
  MntWines: int
  NumCatalogPurchases: int
  NumDealsPurchases: int
  NumStorePurchases: int
  NumWebPurchases: int
  NumWebVisitsMonth: int
  Recency: int
  Response: int
  Teenhome: int
  Year_Birth: int
  Z_CostContact: int
  Z_Revenue: int
categorical_columns:
  Dt_Customer: category
  Education: category
  Marital_Status: category